# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lab5.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Matrita(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(782, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.SvrtkaButton = QtWidgets.QRadioButton(self.centralwidget)
        self.SvrtkaButton.setGeometry(QtCore.QRect(330, 30, 82, 17))
        self.SvrtkaButton.setObjectName("SvrtkaButton")
        self.KarelitiaButton = QtWidgets.QRadioButton(self.centralwidget)
        self.KarelitiaButton.setGeometry(QtCore.QRect(330, 70, 82, 17))
        self.KarelitiaButton.setObjectName("KarelitiaButton")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(480, 40, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(20, 220, 311, 321))
        self.photo.setText("")
        self.photo.setObjectName("photo")
        self.photo_2 = QtWidgets.QLabel(self.centralwidget)
        self.photo_2.setGeometry(QtCore.QRect(416, 220, 351, 331))
        self.photo_2.setText("")
        self.photo_2.setObjectName("photo_2")
        self.photo_2.setStyleSheet("background-color : red")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(76, 182, 121, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(550, 190, 141, 16))
        self.label_2.setObjectName("label_2")
        self.matrix = QtWidgets.QTextEdit(self.centralwidget)
        self.matrix.setGeometry(QtCore.QRect(30, 40, 201, 121))
        self.matrix.setObjectName("matrix")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 20, 47, 13))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 782, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBrowse = QtWidgets.QAction(MainWindow)
        self.actionBrowse.setObjectName("actionBrowse")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menu.addAction(self.actionBrowse)
        self.menu.addAction(self.actionSave)
        self.menu.addAction(self.actionExit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SvrtkaButton.setText(_translate("MainWindow", "Свертка"))
        self.KarelitiaButton.setText(_translate("MainWindow", "Кареляция"))
        self.pushButton.setText(_translate("MainWindow", "Выполнить"))
        self.label.setText(_translate("MainWindow", "Исходное изображение"))
        self.label_2.setText(_translate("MainWindow", "Результат работы"))
        self.label_3.setText(_translate("MainWindow", "Матрица"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.actionBrowse.setText(_translate("MainWindow", "Обзор"))
        self.actionSave.setText(_translate("MainWindow", "Сохранить"))
        self.actionExit.setText(_translate("MainWindow", "Выход"))
